#!/usr/bin/env python3
"""Freeze the ed25519 work out of a captured justification into a fixed corpus.

The signature benchmark should not need a board that is talking to Polkadot.
test/fixtures/finality_proof.bin is a real justification captured by
gen_fixtures.py; every precommit in it signs the same 53-byte localized
payload, which is exactly the shape batch verification wants. This pulls the
payload and the (signature, public key) pairs out of it once, so the host
harness and the device benchmark run on identical, real, unchanging input.

  python3 tools/gen_sig_corpus.py

Writes test/fixtures/ed_corpus.h. Reads no network.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = os.path.join(HERE, "..", "test", "fixtures")


def compact(b, i):
    b0 = b[i]; m = b0 & 3
    if m == 0: return b0 >> 2, i + 1
    if m == 1: return int.from_bytes(b[i:i+2], "little") >> 2, i + 2
    if m == 2: return int.from_bytes(b[i:i+4], "little") >> 2, i + 4
    n = (b0 >> 2) + 4
    return int.from_bytes(b[i+1:i+1+n], "little"), i + 1 + n


def localized_payload(target_hash, target_number, rnd, set_id):
    """Mirror of grandpa_localized_payload() - keep the two in step."""
    return (bytes([1]) + target_hash + target_number.to_bytes(4, "little")
            + rnd.to_bytes(8, "little") + set_id.to_bytes(8, "little"))


def set_id_from_fixtures():
    with open(os.path.join(FIX, "fixtures.h")) as f:
        for line in f:
            if line.startswith("#define FX_SET_ID"):
                return int(line.split()[2].rstrip("uUlL"))
    raise SystemExit("FX_SET_ID not found in fixtures.h")


def carr(name, data, per=12):
    """Flat array."""
    out = [f"static const uint8_t {name} = {{"]
    for i in range(0, len(data), per):
        out.append("    " + "".join("0x%02x," % c for c in data[i:i+per]))
    out.append("};")
    return "\n".join(out)


def carr2(name, data, stride, count, per=16):
    """count x stride array, braced per row so -Wmissing-braces stays quiet."""
    out = [f"static const uint8_t {name}[{count}][{stride}] = {{"]
    for r in range(count):
        row = data[r * stride:(r + 1) * stride]
        body = " ".join("".join("0x%02x," % c for c in row[i:i + per])
                        for i in range(0, stride, per))
        out.append("    { " + body + " },")
    out.append("};")
    return "\n".join(out)


def main():
    set_id = set_id_from_fixtures()
    b = open(os.path.join(FIX, "finality_proof.bin"), "rb").read()

    i = 32                                  # FinalityProof.block, unused
    _just_len, i = compact(b, i)
    rnd = int.from_bytes(b[i:i+8], "little"); i += 8
    target_hash = b[i:i+32]; i += 32
    target_number = int.from_bytes(b[i:i+4], "little"); i += 4
    n, i = compact(b, i)

    payload = localized_payload(target_hash, target_number, rnd, set_id)

    sigs, pks = bytearray(), bytearray()
    kept = 0
    for _ in range(n):
        rec = b[i:i+132]; i += 132
        if len(rec) != 132:
            raise SystemExit("justification truncated")
        # Only votes on the commit target itself are counted by grandpa.c, and
        # only those sign this payload. Votes for a descendant would need
        # votes_ancestries and are skipped there too.
        if rec[:32] != target_hash or rec[32:36] != target_number.to_bytes(4, "little"):
            continue
        sigs += rec[36:100]
        pks += rec[100:132]
        kept += 1

    hdr = f"""/* GENERATED by tools/gen_sig_corpus.py from test/fixtures/finality_proof.bin.
 *
 * {kept} real Polkadot GRANDPA precommit signatures, every one of them over the
 * same {len(payload)}-byte localized payload for round {rnd}, set {set_id}, block
 * {target_number}. All are expected to verify.
 *
 * This is the fixed benchmark input: no board, no network, no chain state, so a
 * change to the verifier can be measured against exactly the bytes the light
 * client sees in production. */
#ifndef ED_CORPUS_H
#define ED_CORPUS_H

#include <stdint.h>

#define ED_CORPUS_N          {kept}u
#define ED_CORPUS_SET_ID     {set_id}ull
#define ED_CORPUS_ROUND      {rnd}ull
#define ED_CORPUS_TARGET_NUM {target_number}u

{carr(f"ED_CORPUS_MSG[{len(payload)}]", payload)}

{carr2("ED_CORPUS_SIG", sigs, 64, kept)}

{carr2("ED_CORPUS_PK", pks, 32, kept)}

#endif
"""
    # carr() emits one flat brace list; C accepts that for a 2-D array.
    out = os.path.join(FIX, "ed_corpus.h")
    open(out, "w").write(hdr)
    print(f"wrote {out}: {kept} signatures, {len(payload)}-byte payload, "
          f"round {rnd}, set {set_id}")
    if kept != n:
        print(f"note: {n - kept} of {n} precommits voted for another target and were skipped")


if __name__ == "__main__":
    main()
