/* GENERATED by tools/gen_checkpoint.py - do not edit by hand.
 *
 * The eight odd multiples A, 3A, ... 15A of each authority key in
 * src/checkpoint.h, decoded and negated exactly as
 * ge25519_frombytes_negate_vartime does, in ref10's ge25519_precomp form.
 *
 * This is a cache, not a second trust root: it is derived from the keys in
 * checkpoint.h and nothing else, and it is bound to them by set_id below.
 * A verification using it accepts and rejects exactly what one without it
 * does. Captured from https://paseo-rpc.n.dwellir.com.
 */
#ifndef CHECKPOINT_PRECOMP_H
#define CHECKPOINT_PRECOMP_H

/* LC_ED25519_PRECOMP is what compiles the 562 KiB of tables in. Without it this
   whole file is empty and the firmware runs the unchanged per-signature path.
   It is deliberately NOT LC_USE_FAST_ED25519: src/mcbench.cpp wants the tables
   while keeping lc_ed25519_verify pointed at the framework's prebuilt libsodium,
   because that prebuilt copy is the in-image anchor every ratio is measured
   against. */
#ifdef LC_ED25519_PRECOMP

#include "ed25519_fast.h"

#define CHECKPOINT_HAVE_PRECOMP    1
/* Checked against CHECKPOINT_SET_ID at compile time by whoever includes both.
   A table built for a rotated set would reject every signature - fail-closed,
   but a fail-closed device is still a broken one, and this catches it at build
   time instead of in the field. */
#define CHECKPOINT_PRECOMP_SET_ID  262ull
#define CHECKPOINT_PRECOMP_COUNT   56

extern const lc_ed25519_pretab
    CHECKPOINT_AUTHORITY_PRECOMP[CHECKPOINT_PRECOMP_COUNT];

#endif
#endif
