// Generated by npm run sync-contract; public chain data only.
import type { AbiEntry } from "@parity/product-sdk/contracts";
export const deployment = {
  "network": "devnet",
  "genesis": "0xd6eec26135305a8ad257a20d003357284c8aa03d0bdb2b357ab0a22371e11ef2",
  "address": "0x0000000000000000000000000000000000000000"
} as const;
export const abi: AbiEntry[] = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "salt",
        "type": "uint256"
      },
      {
        "name": "alice",
        "type": "uint256"
      },
      {
        "name": "bob",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assignKey",
    "inputs": [
      {
        "name": "key",
        "type": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "assignedKey",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledKeys",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setKeyEnabled",
    "inputs": [
      {
        "name": "key",
        "type": "uint32"
      },
      {
        "name": "enabled",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revision",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "InvalidCalldata",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CalldataTooLarge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoSelector",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownSelector",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NonPayableValueReceived",
    "inputs": []
  }
];
